### ISSUE TITLE
Design entity relationship diagram (ERD)

### ISSUE THREAD

**Issue by Adeola-Aderibigbe** [cypherkrescent/inventor-be#1]
**Objectives**

- Create ERD Design of the models

**Comment by Daveohi** [comment]
Link to ER Diagram
https://online.visual-paradigm.com/w/opcndwyp/diagrams/?lightbox=1&highlight=0000ff&edit=https%3A%2F%2Fonline.visual-paradigm.com%2Fw%2Fopcndwyp%2Fdiagrams%2F%23G13NkFZ0guth2b6g-ZNAfPfG3lO2s99x46&editBlankUrl=https%3A%2F%2Fonline.visual-paradigm.com%2Fapp%2Fdiagrams%2F%23diagram%3Aproj%3D0%26vpov%3D16.3%26vpob%3D20220410%26client%3D1%26edit%3D_blank&layers=1&nav=1&vpov=16.3&vpob=20220410#G13NkFZ0guth2b6g-ZNAfPfG3lO2s99x46
